#!/usr/bin/env python3
"""
View all responses generated by the PiscesER1 Marine Support Bot
"""

import sqlite3
import sys

def view_all_responses():
    """View all responses in summary format"""
    conn = sqlite3.connect('pisces_support_bot.db')
    c = conn.cursor()
    
    print("=" * 80)
    print("PISCESER1 MARINE SUPPORT BOT - ALL RESPONSES")
    print("=" * 80)
    
    c.execute('''
        SELECT ticket_id, response_type, confidence_score, generated_at 
        FROM ticket_responses 
        ORDER BY generated_at DESC
    ''')
    
    rows = c.fetchall()
    if not rows:
        print("\nNo responses found in database.")
        return
    
    print(f"\nTotal responses: {len(rows)}\n")
    print(f"{'Ticket ID':<12} {'Type':<18} {'Confidence':<12} {'Generated At'}")
    print("-" * 80)
    
    for row in rows:
        print(f"{row[0]:<12} {row[1]:<18} {row[2]:<12.2f} {row[3]}")
    
    conn.close()

def view_full_response(ticket_id):
    """View full response for a specific ticket"""
    conn = sqlite3.connect('pisces_support_bot.db')
    c = conn.cursor()
    
    c.execute('''
        SELECT ticket_id, response_type, confidence_score, generated_at, response_text, metadata
        FROM ticket_responses 
        WHERE ticket_id = ?
        ORDER BY generated_at DESC
        LIMIT 1
    ''', (ticket_id,))
    
    row = c.fetchone()
    
    if not row:
        print(f"No response found for ticket {ticket_id}")
        return
    
    print("=" * 80)
    print(f"RESPONSE FOR TICKET: {row[0]}")
    print("=" * 80)
    print(f"Response Type: {row[1]}")
    print(f"Confidence Score: {row[2]:.2f}")
    print(f"Generated At: {row[3]}")
    print("-" * 80)
    print("\nFULL RESPONSE:\n")
    print(row[4])
    print("\n" + "=" * 80)
    
    conn.close()

def view_processed_tickets():
    """View all processed tickets"""
    conn = sqlite3.connect('pisces_support_bot.db')
    c = conn.cursor()
    
    print("=" * 80)
    print("PROCESSED TICKETS")
    print("=" * 80)
    
    c.execute('''
        SELECT ticket_id, status, processed_at, error_message
        FROM processed_tickets 
        ORDER BY processed_at DESC
    ''')
    
    rows = c.fetchall()
    if not rows:
        print("\nNo processed tickets found.")
        return
    
    print(f"\nTotal processed: {len(rows)}\n")
    print(f"{'Ticket ID':<12} {'Status':<12} {'Processed At':<30} {'Error'}")
    print("-" * 80)
    
    for row in rows:
        error = row[3][:30] + "..." if row[3] and len(row[3]) > 30 else (row[3] or "-")
        print(f"{row[0]:<12} {row[1]:<12} {row[2]:<30} {error}")
    
    conn.close()

if __name__ == "__main__":
    if len(sys.argv) > 1:
        if sys.argv[1] == "--ticket" and len(sys.argv) > 2:
            view_full_response(sys.argv[2])
        elif sys.argv[1] == "--processed":
            view_processed_tickets()
        else:
            print("Usage:")
            print("  python view_responses.py              # View all responses (summary)")
            print("  python view_responses.py --ticket ID  # View full response for ticket")
            print("  python view_responses.py --processed  # View all processed tickets")
    else:
        view_all_responses()

